### ISSUE TITLE
artisan コマンドがあるディレクトリで実行するとnot found

### ISSUE THREAD

**Issue by yuya-matsushima** [ysugimoto/artisan-findup#1]
macos && Laravel5 において動作を検証しました。

`artisan` ファイルがあるディレクトリで実行した場合に not found となってしまうようです。下記URL部分で意図的にカレントディレクトリを外しているために発生しているようです。

https://github.com/ysugimoto/artisan-findup/blob/master/main.go#L16

**Comment by ysugimoto** [comment]
修正しました、ありがとうございます！
